from dataclasses import dataclass
from typing import List, Optional

BASE_ID = 37370000


@dataclass
class LocationData:
    name: str
    ap_id: int
    region: str = "Fortress"
    goal_only: bool = False  # if True, only relevant for a specific goal
    material_type: str = ""
    df_item: str = ""
    threshold: int = 0


# ── Wealth Milestones ─────────────────────────────────────────────────────────
WEALTH_LOCATIONS: list[LocationData] = [
    LocationData("Humble Beginnings (1,000)",    BASE_ID + 0,  "Fortress"),
    LocationData("Growing Stronghold (10,000)",  BASE_ID + 1,  "Fortress"),
    LocationData("Prosperous Fortress (50,000)", BASE_ID + 2,  "Fortress"),
    LocationData("Rich Citadel (100,000)",       BASE_ID + 3,  "Fortress"),
    LocationData("Legendary Vault (500,000)",    BASE_ID + 4,  "Fortress"),
]

# ── First Production Milestones ───────────────────────────────────────────────
PRODUCTION_LOCATIONS: list[LocationData] = [
    LocationData("First Crafted Item",       BASE_ID + 100, "Fortress"),
    LocationData("First Weapon Forged",      BASE_ID + 101, "Fortress"),
    LocationData("First Armor Crafted",      BASE_ID + 102, "Fortress"),
    LocationData("First Furniture Made",     BASE_ID + 103, "Fortress"),
    LocationData("First Prepared Meal",      BASE_ID + 104, "Fortress"),
    LocationData("First Brew Complete",      BASE_ID + 105, "Fortress"),
    LocationData("First Metal Bar Smelted",  BASE_ID + 106, "Fortress"),
    LocationData("First Block Cut",          BASE_ID + 107, "Fortress"),
    LocationData("First Cloth Woven",        BASE_ID + 108, "Fortress"),
    LocationData("First Leather Tanned",     BASE_ID + 109, "Fortress"),
    LocationData("First Gem Cut",            BASE_ID + 110, "Fortress"),
    LocationData("First Mechanism Made",     BASE_ID + 111, "Fortress"),
    LocationData("First Trap Built",         BASE_ID + 112, "Fortress"),
    LocationData("First Cage Constructed",   BASE_ID + 113, "Fortress"),
    LocationData("First Barrel Made",        BASE_ID + 114, "Fortress"),
    LocationData("First Chest Made",         BASE_ID + 115, "Fortress"),
    LocationData("First Table Made",         BASE_ID + 116, "Fortress"),
    LocationData("First Bed Made",           BASE_ID + 117, "Fortress"),
    LocationData("First Anvil Made",         BASE_ID + 118, "Fortress"),
    LocationData("First Millstone Made",     BASE_ID + 119, "Fortress"),
    LocationData("First Minecart Made",      BASE_ID + 120, "Fortress"),
]

# ── Trade / Export Milestones ─────────────────────────────────────────────────
TRADE_LOCATIONS: list[LocationData] = [
    LocationData("Dwarven Caravan Visit",          BASE_ID + 202, "Fortress"),
    LocationData("Elven Caravan Visit",            BASE_ID + 203, "Fortress"),
    LocationData("Human Caravan Visit",            BASE_ID + 204, "Fortress"),
    LocationData("Outpost Liaison Meeting",        BASE_ID + 205, "Fortress"),
    LocationData("First Raid",                     BASE_ID + 206, "Fortress"),
    LocationData("First Artifact Recovery",        BASE_ID + 207, "Fortress"),
    LocationData("First Act of Diplomacy",         BASE_ID + 208, "Fortress"),
]

# ── Fortress Status / Noble Appointments ──────────────────────────────────────
# IDs match checks.lua (BASE_ID + 300+).
# These track the civilisation's recognition of the fortress, from a mayor-run
# settlement up to a capital with a resident monarch.
STATUS_LOCATIONS: list[LocationData] = [
    LocationData("Mayor Elected",           BASE_ID + 300, "Fortress"),
    LocationData("Baron Appointed",         BASE_ID + 301, "Fortress"),
    LocationData("Count Appointed",         BASE_ID + 302, "Fortress"),
    LocationData("Duke Appointed",          BASE_ID + 303, "Fortress"),
    LocationData("Monarch Takes Residence", BASE_ID + 304, "Fortress"),
]

# ── Fortress Title Milestones ─────────────────────────────────────────────────
# Each title requires population AND either created-wealth OR exported-wealth.
# See https://dwarffortresswiki.org/index.php/Fortress
TITLE_LOCATIONS: list[LocationData] = [
    LocationData("Hamlet Established",      BASE_ID + 400, "Fortress"),
    LocationData("Village Established",     BASE_ID + 401, "Fortress"),
    LocationData("Town Established",        BASE_ID + 402, "Fortress"),
    LocationData("City Established",        BASE_ID + 403, "Fortress"),
    LocationData("Metropolis Established",  BASE_ID + 404, "Fortress"),
]


# ── Mining Milestones ─────────────────────────────────────────────────────────
# Depth = surface z-level minus the deepest z any mining job has reached.
# Tiles = cumulative count of completed dig/channel/staircase/ramp jobs.
# IDs match checks.lua (BASE_ID + 700 depth, +710 tiles).
MINING_LOCATIONS: list[LocationData] = [
    LocationData("Delved 10 Levels Deep",       BASE_ID + 700, "Fortress"),
    LocationData("Delved 25 Levels Deep",       BASE_ID + 701, "Fortress"),
    LocationData("Delved 50 Levels Deep",       BASE_ID + 702, "Fortress"),
    LocationData("Delved 75 Levels Deep",       BASE_ID + 703, "Fortress"),
    LocationData("Delved 100 Levels Deep",      BASE_ID + 704, "Fortress"),
    LocationData("Excavator I (100 tiles)",     BASE_ID + 710, "Fortress"),
    LocationData("Excavator II (500 tiles)",    BASE_ID + 711, "Fortress"),
    LocationData("Excavator III (2,000 tiles)", BASE_ID + 712, "Fortress"),
    LocationData("Excavator IV (5,000 tiles)",  BASE_ID + 713, "Fortress"),
    LocationData("Excavator V (10,000 tiles)",  BASE_ID + 714, "Fortress"),
    LocationData("First Cavern Breached",        BASE_ID + 720, "Fortress"),
    LocationData("Second Cavern Breached",       BASE_ID + 721, "Fortress"),
    LocationData("Third Cavern Breached",        BASE_ID + 722, "Fortress"),
    LocationData("Reached the Magma Sea",        BASE_ID + 723, "Fortress"),
    LocationData("Welcome to the Circus",          BASE_ID + 724, "Fortress"),
]

# ── Farming Milestones ────────────────────────────────────────────────────────
# Cumulative count of harvested crops (PLANT items created). IDs match checks.lua
# (BASE_ID + 730).
FARMING_LOCATIONS: list[LocationData] = [
    LocationData("Harvest 50 Crops",    BASE_ID + 730, "Fortress"),
    LocationData("Harvest 100 Crops",   BASE_ID + 731, "Fortress"),
    LocationData("Harvest 250 Crops",   BASE_ID + 732, "Fortress"),
    LocationData("Harvest 500 Crops",   BASE_ID + 733, "Fortress"),
    LocationData("Harvest 1,000 Crops", BASE_ID + 734, "Fortress"),
]

# ── Infrastructure Milestones ─────────────────────────────────────────────────
INFRASTRUCTURE_LOCATIONS: list[LocationData] = [
    LocationData("Built a Well",   BASE_ID + 740, "Fortress"),
    LocationData("Pumped Water",   BASE_ID + 741, "Fortress"),
    LocationData("Pumped Magma",   BASE_ID + 742, "Fortress"),
]

# ── Biology / Animal Milestones ───────────────────────────────────────────────
BIOLOGY_LOCATIONS: list[LocationData] = [
    # "First Eggs Hatched" (BASE_ID + 750) disabled: hatch detection unreliable on DF v50.
    # LocationData("First Eggs Hatched",  BASE_ID + 750, "Fortress"),
    LocationData("Caged a Hostile Beast",   BASE_ID + 751, "Fortress"),
]

# ── Deep / Endgame Milestones ─────────────────────────────────────────────────
ENDGAME_LOCATIONS: list[LocationData] = [
    LocationData("Mined Adamantine",  BASE_ID + 760, "Fortress"),
    LocationData("Sold an Artifact",  BASE_ID + 761, "Fortress"),
]

JOB_SKILLS: list[LocationData] = [
    LocationData("Novice Stonecutter",         BASE_ID + 800, "Fortress"),
    LocationData("Adequate Stonecutter",       BASE_ID + 801, "Fortress"),
    LocationData("Competent Stonecutter",      BASE_ID + 802, "Fortress"),
    LocationData("Skilled Stonecutter",        BASE_ID + 803, "Fortress"),
    LocationData("Proficient Stonecutter",     BASE_ID + 804, "Fortress"),
    LocationData("Talented Stonecutter",       BASE_ID + 805, "Fortress"),
    LocationData("Adept Stonecutter",          BASE_ID + 806, "Fortress"),
    LocationData("Expert Stonecutter",         BASE_ID + 807, "Fortress"),
    LocationData("Professional Stonecutter",   BASE_ID + 808, "Fortress"),
    LocationData("Accomplished Stonecutter",   BASE_ID + 809, "Fortress"),
    LocationData("Great Stonecutter",          BASE_ID + 810, "Fortress"),
    LocationData("Master Stonecutter",         BASE_ID + 811, "Fortress"),
    LocationData("High Master Stonecutter",    BASE_ID + 812, "Fortress"),
    LocationData("Grand Master Stonecutter",   BASE_ID + 813, "Fortress"),
    LocationData("Legendary Stonecutter",      BASE_ID + 814, "Fortress"),

    LocationData("Novice Engraver",             BASE_ID + 815, "Fortress"),
    LocationData("Adequate Engraver",           BASE_ID + 816, "Fortress"),
    LocationData("Competent Engraver",          BASE_ID + 817, "Fortress"),
    LocationData("Skilled Engraver",            BASE_ID + 818, "Fortress"),
    LocationData("Proficient Engraver",         BASE_ID + 819, "Fortress"),
    LocationData("Talented Engraver",           BASE_ID + 820, "Fortress"),
    LocationData("Adept Engraver",              BASE_ID + 821, "Fortress"),
    LocationData("Expert Engraver",             BASE_ID + 822, "Fortress"),
    LocationData("Professional Engraver",       BASE_ID + 823, "Fortress"),
    LocationData("Accomplished Engraver",       BASE_ID + 824, "Fortress"),
    LocationData("Great Engraver",              BASE_ID + 825, "Fortress"),
    LocationData("Master Engraver",             BASE_ID + 826, "Fortress"),
    LocationData("High Master Engraver",        BASE_ID + 827, "Fortress"),
    LocationData("Grand Master Engraver",       BASE_ID + 828, "Fortress"),
    LocationData("Legendary Engraver",          BASE_ID + 829, "Fortress"),

    LocationData("Novice Miner",                BASE_ID + 830, "Fortress"),
    LocationData("Adequate Miner",              BASE_ID + 831, "Fortress"),
    LocationData("Competent Miner",             BASE_ID + 832, "Fortress"),
    LocationData("Skilled Miner",               BASE_ID + 833, "Fortress"),
    LocationData("Proficient Miner",            BASE_ID + 834, "Fortress"),
    LocationData("Talented Miner",              BASE_ID + 835, "Fortress"),
    LocationData("Adept Miner",                 BASE_ID + 836, "Fortress"),
    LocationData("Expert Miner",                BASE_ID + 837, "Fortress"),
    LocationData("Professional Miner",          BASE_ID + 838, "Fortress"),
    LocationData("Accomplished Miner",          BASE_ID + 839, "Fortress"),
    LocationData("Great Miner",                 BASE_ID + 840, "Fortress"),
    LocationData("Master Miner",                BASE_ID + 841, "Fortress"),
    LocationData("High Master Miner",           BASE_ID + 842, "Fortress"),
    LocationData("Grand Master Miner",          BASE_ID + 843, "Fortress"),
    LocationData("Legendary Miner",             BASE_ID + 844, "Fortress"),

    LocationData("Novice Wood Cutter",          BASE_ID + 845, "Fortress"),
    LocationData("Adequate Wood Cutter",        BASE_ID + 846, "Fortress"),
    LocationData("Competent Wood Cutter",       BASE_ID + 847, "Fortress"),
    LocationData("Skilled Wood Cutter",         BASE_ID + 848, "Fortress"),
    LocationData("Proficient Wood Cutter",      BASE_ID + 849, "Fortress"),
    LocationData("Talented Wood Cutter",        BASE_ID + 850, "Fortress"),
    LocationData("Adept Wood Cutter",           BASE_ID + 851, "Fortress"),
    LocationData("Expert Wood Cutter",          BASE_ID + 852, "Fortress"),
    LocationData("Professional Wood Cutter",    BASE_ID + 853, "Fortress"),
    LocationData("Accomplished Wood Cutter",    BASE_ID + 854, "Fortress"),
    LocationData("Great Wood Cutter",           BASE_ID + 855, "Fortress"),
    LocationData("Master Wood Cutter",          BASE_ID + 856, "Fortress"),
    LocationData("High Master Wood Cutter",     BASE_ID + 857, "Fortress"),
    LocationData("Grand Master Wood Cutter",    BASE_ID + 858, "Fortress"),
    LocationData("Legendary Wood Cutter",       BASE_ID + 859, "Fortress"),

    LocationData("Novice Herbalist",            BASE_ID + 860, "Fortress"),
    LocationData("Adequate Herbalist",          BASE_ID + 861, "Fortress"),
    LocationData("Competent Herbalist",         BASE_ID + 862, "Fortress"),
    LocationData("Skilled Herbalist",           BASE_ID + 863, "Fortress"),
    LocationData("Proficient Herbalist",        BASE_ID + 864, "Fortress"),
    LocationData("Talented Herbalist",          BASE_ID + 865, "Fortress"),
    LocationData("Adept Herbalist",             BASE_ID + 866, "Fortress"),
    LocationData("Expert Herbalist",            BASE_ID + 867, "Fortress"),
    LocationData("Professional Herbalist",      BASE_ID + 868, "Fortress"),
    LocationData("Accomplished Herbalist",      BASE_ID + 869, "Fortress"),
    LocationData("Great Herbalist",             BASE_ID + 870, "Fortress"),
    LocationData("Master Herbalist",            BASE_ID + 871, "Fortress"),
    LocationData("High Master Herbalist",       BASE_ID + 872, "Fortress"),
    LocationData("Grand Master Herbalist",      BASE_ID + 873, "Fortress"),
    LocationData("Legendary Herbalist",         BASE_ID + 874, "Fortress"),

    LocationData("Novice Spinner",              BASE_ID + 875, "Fortress"),
    LocationData("Adequate Spinner",            BASE_ID + 876, "Fortress"),
    LocationData("Competent Spinner",           BASE_ID + 877, "Fortress"),
    LocationData("Skilled Spinner",             BASE_ID + 878, "Fortress"),
    LocationData("Proficient Spinner",          BASE_ID + 879, "Fortress"),
    LocationData("Talented Spinner",            BASE_ID + 880, "Fortress"),
    LocationData("Adept Spinner",               BASE_ID + 881, "Fortress"),
    LocationData("Expert Spinner",              BASE_ID + 882, "Fortress"),
    LocationData("Professional Spinner",        BASE_ID + 883, "Fortress"),
    LocationData("Accomplished Spinner",        BASE_ID + 884, "Fortress"),
    LocationData("Great Spinner",               BASE_ID + 885, "Fortress"),
    LocationData("Master Spinner",              BASE_ID + 886, "Fortress"),
    LocationData("High Master Spinner",         BASE_ID + 887, "Fortress"),
    LocationData("Grand Master Spinner",        BASE_ID + 888, "Fortress"),
    LocationData("Legendary Spinner",           BASE_ID + 889, "Fortress"),

    LocationData("Novice Fisherdwarf",          BASE_ID + 890, "Fortress"),
    LocationData("Adequate Fisherdwarf",        BASE_ID + 891, "Fortress"),
    LocationData("Competent Fisherdwarf",       BASE_ID + 892, "Fortress"),
    LocationData("Skilled Fisherdwarf",         BASE_ID + 893, "Fortress"),
    LocationData("Proficient Fisherdwarf",      BASE_ID + 894, "Fortress"),
    LocationData("Talented Fisherdwarf",        BASE_ID + 895, "Fortress"),
    LocationData("Adept Fisherdwarf",           BASE_ID + 896, "Fortress"),
    LocationData("Expert Fisherdwarf",          BASE_ID + 897, "Fortress"),
    LocationData("Professional Fisherdwarf",    BASE_ID + 898, "Fortress"),
    LocationData("Accomplished Fisherdwarf",    BASE_ID + 899, "Fortress"),
    LocationData("Great Fisherdwarf",           BASE_ID + 900, "Fortress"),
    LocationData("Master Fisherdwarf",          BASE_ID + 901, "Fortress"),
    LocationData("High Master Fisherdwarf",     BASE_ID + 902, "Fortress"),
    LocationData("Grand Master Fisherdwarf",    BASE_ID + 903, "Fortress"),
    LocationData("Legendary Fisherdwarf",       BASE_ID + 904, "Fortress"),

    LocationData("Novice Ambusher",             BASE_ID + 905, "Fortress"),
    LocationData("Adequate Ambusher",           BASE_ID + 906, "Fortress"),
    LocationData("Competent Ambusher",          BASE_ID + 907, "Fortress"),
    LocationData("Skilled Ambusher",            BASE_ID + 908, "Fortress"),
    LocationData("Proficient Ambusher",         BASE_ID + 909, "Fortress"),
    LocationData("Talented Ambusher",           BASE_ID + 910, "Fortress"),
    LocationData("Adept Ambusher",              BASE_ID + 911, "Fortress"),
    LocationData("Expert Ambusher",             BASE_ID + 912, "Fortress"),
    LocationData("Professional Ambusher",       BASE_ID + 913, "Fortress"),
    LocationData("Accomplished Ambusher",       BASE_ID + 914, "Fortress"),
    LocationData("Great Ambusher",              BASE_ID + 915, "Fortress"),
    LocationData("Master Ambusher",             BASE_ID + 916, "Fortress"),
    LocationData("High Master Ambusher",        BASE_ID + 917, "Fortress"),
    LocationData("Grand Master Ambusher",       BASE_ID + 918, "Fortress"),
    LocationData("Legendary Ambusher",          BASE_ID + 919, "Fortress"),

    LocationData("Novice Trapper",              BASE_ID + 920, "Fortress"),
    LocationData("Adequate Trapper",            BASE_ID + 921, "Fortress"),
    LocationData("Competent Trapper",           BASE_ID + 922, "Fortress"),
    LocationData("Skilled Trapper",             BASE_ID + 923, "Fortress"),
    LocationData("Proficient Trapper",          BASE_ID + 924, "Fortress"),
    LocationData("Talented Trapper",            BASE_ID + 925, "Fortress"),
    LocationData("Adept Trapper",               BASE_ID + 926, "Fortress"),
    LocationData("Expert Trapper",              BASE_ID + 927, "Fortress"),
    LocationData("Professional Trapper",        BASE_ID + 928, "Fortress"),
    LocationData("Accomplished Trapper",        BASE_ID + 929, "Fortress"),
    LocationData("Great Trapper",               BASE_ID + 930, "Fortress"),
    LocationData("Master Trapper",              BASE_ID + 931, "Fortress"),
    LocationData("High Master Trapper",         BASE_ID + 932, "Fortress"),
    LocationData("Grand Master Trapper",        BASE_ID + 933, "Fortress"),
    LocationData("Legendary Trapper",           BASE_ID + 934, "Fortress"),

    LocationData("Novice Glassmaker",           BASE_ID + 935, "Fortress"),
    LocationData("Adequate Glassmaker",         BASE_ID + 936, "Fortress"),
    LocationData("Competent Glassmaker",        BASE_ID + 937, "Fortress"),
    LocationData("Skilled Glassmaker",          BASE_ID + 938, "Fortress"),
    LocationData("Proficient Glassmaker",       BASE_ID + 939, "Fortress"),
    LocationData("Talented Glassmaker",         BASE_ID + 940, "Fortress"),
    LocationData("Adept Glassmaker",            BASE_ID + 941, "Fortress"),
    LocationData("Expert Glassmaker",           BASE_ID + 942, "Fortress"),
    LocationData("Professional Glassmaker",     BASE_ID + 943, "Fortress"),
    LocationData("Accomplished Glassmaker",     BASE_ID + 944, "Fortress"),
    LocationData("Great Glassmaker",            BASE_ID + 945, "Fortress"),
    LocationData("Master Glassmaker",           BASE_ID + 946, "Fortress"),
    LocationData("High Master Glassmaker",      BASE_ID + 947, "Fortress"),
    LocationData("Grand Master Glassmaker",     BASE_ID + 948, "Fortress"),
    LocationData("Legendary Glassmaker",        BASE_ID + 949, "Fortress"),

    LocationData("Novice Metal Crafter",        BASE_ID + 950, "Fortress"),
    LocationData("Adequate Metal Crafter",      BASE_ID + 951, "Fortress"),
    LocationData("Competent Metal Crafter",     BASE_ID + 952, "Fortress"),
    LocationData("Skilled Metal Crafter",       BASE_ID + 953, "Fortress"),
    LocationData("Proficient Metal Crafter",    BASE_ID + 954, "Fortress"),
    LocationData("Talented Metal Crafter",      BASE_ID + 955, "Fortress"),
    LocationData("Adept Metal Crafter",         BASE_ID + 956, "Fortress"),
    LocationData("Expert Metal Crafter",        BASE_ID + 957, "Fortress"),
    LocationData("Professional Metal Crafter",  BASE_ID + 958, "Fortress"),
    LocationData("Accomplished Metal Crafter",  BASE_ID + 959, "Fortress"),
    LocationData("Great Metal Crafter",         BASE_ID + 960, "Fortress"),
    LocationData("Master Metal Crafter",        BASE_ID + 961, "Fortress"),
    LocationData("High Master Metal Crafter",   BASE_ID + 962, "Fortress"),
    LocationData("Grand Master Metal Crafter",  BASE_ID + 963, "Fortress"),
    LocationData("Legendary Metal Crafter",     BASE_ID + 964, "Fortress"),

    LocationData("Novice Gem Cutter",           BASE_ID + 965, "Fortress"),
    LocationData("Adequate Gem Cutter",         BASE_ID + 966, "Fortress"),
    LocationData("Competent Gem Cutter",        BASE_ID + 967, "Fortress"),
    LocationData("Skilled Gem Cutter",          BASE_ID + 968, "Fortress"),
    LocationData("Proficient Gem Cutter",       BASE_ID + 969, "Fortress"),
    LocationData("Talented Gem Cutter",         BASE_ID + 970, "Fortress"),
    LocationData("Adept Gem Cutter",            BASE_ID + 971, "Fortress"),
    LocationData("Expert Gem Cutter",           BASE_ID + 972, "Fortress"),
    LocationData("Professional Gem Cutter",     BASE_ID + 973, "Fortress"),
    LocationData("Accomplished Gem Cutter",     BASE_ID + 974, "Fortress"),
    LocationData("Great Gem Cutter",            BASE_ID + 975, "Fortress"),
    LocationData("Master Gem Cutter",           BASE_ID + 976, "Fortress"),
    LocationData("High Master Gem Cutter",      BASE_ID + 977, "Fortress"),
    LocationData("Grand Master Gem Cutter",     BASE_ID + 978, "Fortress"),
    LocationData("Legendary Gem Cutter",        BASE_ID + 979, "Fortress"),

    LocationData("Novice Stone Crafter",        BASE_ID + 980, "Fortress"),
    LocationData("Adequate Stone Crafter",      BASE_ID + 981, "Fortress"),
    LocationData("Competent Stone Crafter",     BASE_ID + 982, "Fortress"),
    LocationData("Skilled Stone Crafter",       BASE_ID + 983, "Fortress"),
    LocationData("Proficient Stone Crafter",    BASE_ID + 984, "Fortress"),
    LocationData("Talented Stone Crafter",      BASE_ID + 985, "Fortress"),
    LocationData("Adept Stone Crafter",         BASE_ID + 986, "Fortress"),
    LocationData("Expert Stone Crafter",        BASE_ID + 987, "Fortress"),
    LocationData("Professional Stone Crafter",  BASE_ID + 988, "Fortress"),
    LocationData("Accomplished Stone Crafter",  BASE_ID + 989, "Fortress"),
    LocationData("Great Stone Crafter",         BASE_ID + 990, "Fortress"),
    LocationData("Master Stone Crafter",        BASE_ID + 991, "Fortress"),
    LocationData("High Master Stone Crafter",   BASE_ID + 992, "Fortress"),
    LocationData("Grand Master Stone Crafter",  BASE_ID + 993, "Fortress"),
    LocationData("Legendary Stone Crafter",     BASE_ID + 994, "Fortress"),

    LocationData("Novice Wood Crafter",         BASE_ID + 995, "Fortress"),
    LocationData("Adequate Wood Crafter",       BASE_ID + 996, "Fortress"),
    LocationData("Competent Wood Crafter",      BASE_ID + 997, "Fortress"),
    LocationData("Skilled Wood Crafter",        BASE_ID + 998, "Fortress"),
    LocationData("Proficient Wood Crafter",     BASE_ID + 999, "Fortress"),
    LocationData("Talented Wood Crafter",       BASE_ID + 1000, "Fortress"),
    LocationData("Adept Wood Crafter",          BASE_ID + 1001, "Fortress"),
    LocationData("Expert Wood Crafter",         BASE_ID + 1002, "Fortress"),
    LocationData("Professional Wood Crafter",   BASE_ID + 1003, "Fortress"),
    LocationData("Accomplished Wood Crafter",   BASE_ID + 1004, "Fortress"),
    LocationData("Great Wood Crafter",          BASE_ID + 1005, "Fortress"),
    LocationData("Master Wood Crafter",         BASE_ID + 1006, "Fortress"),
    LocationData("High Master Wood Crafter",    BASE_ID + 1007, "Fortress"),
    LocationData("Grand Master Wood Crafter",   BASE_ID + 1008, "Fortress"),
    LocationData("Legendary Wood Crafter",      BASE_ID + 1009, "Fortress"),

    LocationData("Novice Gem Setter",           BASE_ID + 1010, "Fortress"),
    LocationData("Adequate Gem Setter",         BASE_ID + 1011, "Fortress"),
    LocationData("Competent Gem Setter",        BASE_ID + 1012, "Fortress"),
    LocationData("Skilled Gem Setter",          BASE_ID + 1013, "Fortress"),
    LocationData("Proficient Gem Setter",       BASE_ID + 1014, "Fortress"),
    LocationData("Talented Gem Setter",         BASE_ID + 1015, "Fortress"),
    LocationData("Adept Gem Setter",            BASE_ID + 1016, "Fortress"),
    LocationData("Expert Gem Setter",           BASE_ID + 1017, "Fortress"),
    LocationData("Professional Gem Setter",     BASE_ID + 1018, "Fortress"),
    LocationData("Accomplished Gem Setter",     BASE_ID + 1019, "Fortress"),
    LocationData("Great Gem Setter",            BASE_ID + 1020, "Fortress"),
    LocationData("Master Gem Setter",           BASE_ID + 1021, "Fortress"),
    LocationData("High Master Gem Setter",      BASE_ID + 1022, "Fortress"),
    LocationData("Grand Master Gem Setter",     BASE_ID + 1023, "Fortress"),
    LocationData("Legendary Gem Setter",        BASE_ID + 1024, "Fortress"),

    LocationData("Novice Furnace Operator",     BASE_ID + 1025, "Fortress"),
    LocationData("Adequate Furnace Operator",   BASE_ID + 1026, "Fortress"),
    LocationData("Competent Furnace Operator",  BASE_ID + 1027, "Fortress"),
    LocationData("Skilled Furnace Operator",    BASE_ID + 1028, "Fortress"),
    LocationData("Proficient Furnace Operator", BASE_ID + 1029, "Fortress"),
    LocationData("Talented Furnace Operator",   BASE_ID + 1030, "Fortress"),
    LocationData("Adept Furnace Operator",      BASE_ID + 1031, "Fortress"),
    LocationData("Expert Furnace Operator",     BASE_ID + 1032, "Fortress"),
    LocationData("Professional Furnace Operator", BASE_ID + 1033, "Fortress"),
    LocationData("Accomplished Furnace Operator", BASE_ID + 1034, "Fortress"),
    LocationData("Great Furnace Operator",      BASE_ID + 1035, "Fortress"),
    LocationData("Master Furnace Operator",     BASE_ID + 1036, "Fortress"),
    LocationData("High Master Furnace Operator",  BASE_ID + 1037, "Fortress"),
    LocationData("Grand Master Furnace Operator", BASE_ID + 1038, "Fortress"),
    LocationData("Legendary Furnace Operator",  BASE_ID + 1039, "Fortress"),

    LocationData("Novice Strand Extractor",     BASE_ID + 1040, "Fortress"),
    LocationData("Adequate Strand Extractor",   BASE_ID + 1041, "Fortress"),
    LocationData("Competent Strand Extractor",  BASE_ID + 1042, "Fortress"),
    LocationData("Skilled Strand Extractor",    BASE_ID + 1043, "Fortress"),
    LocationData("Proficient Strand Extractor", BASE_ID + 1044, "Fortress"),
    LocationData("Talented Strand Extractor",   BASE_ID + 1045, "Fortress"),
    LocationData("Adept Strand Extractor",      BASE_ID + 1046, "Fortress"),
    LocationData("Expert Strand Extractor",     BASE_ID + 1047, "Fortress"),
    LocationData("Professional Strand Extractor", BASE_ID + 1048, "Fortress"),
    LocationData("Accomplished Strand Extractor", BASE_ID + 1049, "Fortress"),
    LocationData("Great Strand Extractor",      BASE_ID + 1050, "Fortress"),
    LocationData("Master Strand Extractor",     BASE_ID + 1051, "Fortress"),
    LocationData("High Master Strand Extractor",  BASE_ID + 1052, "Fortress"),
    LocationData("Grand Master Strand Extractor", BASE_ID + 1053, "Fortress"),
    LocationData("Legendary Strand Extractor",  BASE_ID + 1054, "Fortress"),

    LocationData("Novice Planter",              BASE_ID + 1055, "Fortress"),
    LocationData("Adequate Planter",            BASE_ID + 1056, "Fortress"),
    LocationData("Competent Planter",           BASE_ID + 1057, "Fortress"),
    LocationData("Skilled Planter",             BASE_ID + 1058, "Fortress"),
    LocationData("Proficient Planter",          BASE_ID + 1059, "Fortress"),
    LocationData("Talented Planter",            BASE_ID + 1060, "Fortress"),
    LocationData("Adept Planter",               BASE_ID + 1061, "Fortress"),
    LocationData("Expert Planter",              BASE_ID + 1062, "Fortress"),
    LocationData("Professional Planter",        BASE_ID + 1063, "Fortress"),
    LocationData("Accomplished Planter",        BASE_ID + 1064, "Fortress"),
    LocationData("Great Planter",               BASE_ID + 1065, "Fortress"),
    LocationData("Master Planter",              BASE_ID + 1066, "Fortress"),
    LocationData("High Master Planter",         BASE_ID + 1067, "Fortress"),
    LocationData("Grand Master Planter",        BASE_ID + 1068, "Fortress"),
    LocationData("Legendary Planter",           BASE_ID + 1069, "Fortress"),

    LocationData("Novice Animal Trainer",       BASE_ID + 1070, "Fortress"),
    LocationData("Adequate Animal Trainer",     BASE_ID + 1071, "Fortress"),
    LocationData("Competent Animal Trainer",    BASE_ID + 1072, "Fortress"),
    LocationData("Skilled Animal Trainer",      BASE_ID + 1073, "Fortress"),
    LocationData("Proficient Animal Trainer",   BASE_ID + 1074, "Fortress"),
    LocationData("Talented Animal Trainer",     BASE_ID + 1075, "Fortress"),
    LocationData("Adept Animal Trainer",        BASE_ID + 1076, "Fortress"),
    LocationData("Expert Animal Trainer",       BASE_ID + 1077, "Fortress"),
    LocationData("Professional Animal Trainer", BASE_ID + 1078, "Fortress"),
    LocationData("Accomplished Animal Trainer", BASE_ID + 1079, "Fortress"),
    LocationData("Great Animal Trainer",        BASE_ID + 1080, "Fortress"),
    LocationData("Master Animal Trainer",       BASE_ID + 1081, "Fortress"),
    LocationData("High Master Animal Trainer",  BASE_ID + 1082, "Fortress"),
    LocationData("Grand Master Animal Trainer", BASE_ID + 1083, "Fortress"),
    LocationData("Legendary Animal Trainer",    BASE_ID + 1084, "Fortress"),

    LocationData("Novice Siege Engineer",       BASE_ID + 1085, "Fortress"),
    LocationData("Adequate Siege Engineer",     BASE_ID + 1086, "Fortress"),
    LocationData("Competent Siege Engineer",    BASE_ID + 1087, "Fortress"),
    LocationData("Skilled Siege Engineer",      BASE_ID + 1088, "Fortress"),
    LocationData("Proficient Siege Engineer",   BASE_ID + 1089, "Fortress"),
    LocationData("Talented Siege Engineer",     BASE_ID + 1090, "Fortress"),
    LocationData("Adept Siege Engineer",        BASE_ID + 1091, "Fortress"),
    LocationData("Expert Siege Engineer",       BASE_ID + 1092, "Fortress"),
    LocationData("Professional Siege Engineer", BASE_ID + 1093, "Fortress"),
    LocationData("Accomplished Siege Engineer", BASE_ID + 1094, "Fortress"),
    LocationData("Great Siege Engineer",        BASE_ID + 1095, "Fortress"),
    LocationData("Master Siege Engineer",       BASE_ID + 1096, "Fortress"),
    LocationData("High Master Siege Engineer",  BASE_ID + 1097, "Fortress"),
    LocationData("Grand Master Siege Engineer", BASE_ID + 1098, "Fortress"),
    LocationData("Legendary Siege Engineer",    BASE_ID + 1099, "Fortress"),

    LocationData("Novice Weaponsmith",          BASE_ID + 1100, "Fortress"),
    LocationData("Adequate Weaponsmith",        BASE_ID + 1101, "Fortress"),
    LocationData("Competent Weaponsmith",       BASE_ID + 1102, "Fortress"),
    LocationData("Skilled Weaponsmith",         BASE_ID + 1103, "Fortress"),
    LocationData("Proficient Weaponsmith",      BASE_ID + 1104, "Fortress"),
    LocationData("Talented Weaponsmith",        BASE_ID + 1105, "Fortress"),
    LocationData("Adept Weaponsmith",           BASE_ID + 1106, "Fortress"),
    LocationData("Expert Weaponsmith",          BASE_ID + 1107, "Fortress"),
    LocationData("Professional Weaponsmith",    BASE_ID + 1108, "Fortress"),
    LocationData("Accomplished Weaponsmith",    BASE_ID + 1109, "Fortress"),
    LocationData("Great Weaponsmith",           BASE_ID + 1110, "Fortress"),
    LocationData("Master Weaponsmith",          BASE_ID + 1111, "Fortress"),
    LocationData("High Master Weaponsmith",     BASE_ID + 1112, "Fortress"),
    LocationData("Grand Master Weaponsmith",    BASE_ID + 1113, "Fortress"),
    LocationData("Legendary Weaponsmith",       BASE_ID + 1114, "Fortress"),

    LocationData("Novice Armorsmith",           BASE_ID + 1115, "Fortress"),
    LocationData("Adequate Armorsmith",         BASE_ID + 1116, "Fortress"),
    LocationData("Competent Armorsmith",        BASE_ID + 1117, "Fortress"),
    LocationData("Skilled Armorsmith",          BASE_ID + 1118, "Fortress"),
    LocationData("Proficient Armorsmith",       BASE_ID + 1119, "Fortress"),
    LocationData("Talented Armorsmith",         BASE_ID + 1120, "Fortress"),
    LocationData("Adept Armorsmith",            BASE_ID + 1121, "Fortress"),
    LocationData("Expert Armorsmith",           BASE_ID + 1122, "Fortress"),
    LocationData("Professional Armorsmith",     BASE_ID + 1123, "Fortress"),
    LocationData("Accomplished Armorsmith",     BASE_ID + 1124, "Fortress"),
    LocationData("Great Armorsmith",            BASE_ID + 1125, "Fortress"),
    LocationData("Master Armorsmith",           BASE_ID + 1126, "Fortress"),
    LocationData("High Master Armorsmith",      BASE_ID + 1127, "Fortress"),
    LocationData("Grand Master Armorsmith",     BASE_ID + 1128, "Fortress"),
    LocationData("Legendary Armorsmith",        BASE_ID + 1129, "Fortress"),

    LocationData("Novice Butcher",              BASE_ID + 1130, "Fortress"),
    LocationData("Adequate Butcher",            BASE_ID + 1131, "Fortress"),
    LocationData("Competent Butcher",           BASE_ID + 1132, "Fortress"),
    LocationData("Skilled Butcher",             BASE_ID + 1133, "Fortress"),
    LocationData("Proficient Butcher",          BASE_ID + 1134, "Fortress"),
    LocationData("Talented Butcher",            BASE_ID + 1135, "Fortress"),
    LocationData("Adept Butcher",               BASE_ID + 1136, "Fortress"),
    LocationData("Expert Butcher",              BASE_ID + 1137, "Fortress"),
    LocationData("Professional Butcher",        BASE_ID + 1138, "Fortress"),
    LocationData("Accomplished Butcher",        BASE_ID + 1139, "Fortress"),
    LocationData("Great Butcher",               BASE_ID + 1140, "Fortress"),
    LocationData("Master Butcher",              BASE_ID + 1141, "Fortress"),
    LocationData("High Master Butcher",         BASE_ID + 1142, "Fortress"),
    LocationData("Grand Master Butcher",        BASE_ID + 1143, "Fortress"),
    LocationData("Legendary Butcher",           BASE_ID + 1144, "Fortress"),

    LocationData("Novice Fish Cleaner",         BASE_ID + 1145, "Fortress"),
    LocationData("Adequate Fish Cleaner",       BASE_ID + 1146, "Fortress"),
    LocationData("Competent Fish Cleaner",      BASE_ID + 1147, "Fortress"),
    LocationData("Skilled Fish Cleaner",        BASE_ID + 1148, "Fortress"),
    LocationData("Proficient Fish Cleaner",     BASE_ID + 1149, "Fortress"),
    LocationData("Talented Fish Cleaner",       BASE_ID + 1150, "Fortress"),
    LocationData("Adept Fish Cleaner",          BASE_ID + 1151, "Fortress"),
    LocationData("Expert Fish Cleaner",         BASE_ID + 1152, "Fortress"),
    LocationData("Professional Fish Cleaner",   BASE_ID + 1153, "Fortress"),
    LocationData("Accomplished Fish Cleaner",   BASE_ID + 1154, "Fortress"),
    LocationData("Great Fish Cleaner",          BASE_ID + 1155, "Fortress"),
    LocationData("Master Fish Cleaner",         BASE_ID + 1156, "Fortress"),
    LocationData("High Master Fish Cleaner",    BASE_ID + 1157, "Fortress"),
    LocationData("Grand Master Fish Cleaner",   BASE_ID + 1158, "Fortress"),
    LocationData("Legendary Fish Cleaner",      BASE_ID + 1159, "Fortress"),

    LocationData("Novice Miller",               BASE_ID + 1160, "Fortress"),
    LocationData("Adequate Miller",             BASE_ID + 1161, "Fortress"),
    LocationData("Competent Miller",            BASE_ID + 1162, "Fortress"),
    LocationData("Skilled Miller",              BASE_ID + 1163, "Fortress"),
    LocationData("Proficient Miller",           BASE_ID + 1164, "Fortress"),
    LocationData("Talented Miller",             BASE_ID + 1165, "Fortress"),
    LocationData("Adept Miller",                BASE_ID + 1166, "Fortress"),
    LocationData("Expert Miller",               BASE_ID + 1167, "Fortress"),
    LocationData("Professional Miller",         BASE_ID + 1168, "Fortress"),
    LocationData("Accomplished Miller",         BASE_ID + 1169, "Fortress"),
    LocationData("Great Miller",                BASE_ID + 1170, "Fortress"),
    LocationData("Master Miller",               BASE_ID + 1171, "Fortress"),
    LocationData("High Master Miller",          BASE_ID + 1172, "Fortress"),
    LocationData("Grand Master Miller",         BASE_ID + 1173, "Fortress"),
    LocationData("Legendary Miller",            BASE_ID + 1174, "Fortress"),

    LocationData("Novice Milker",               BASE_ID + 1175, "Fortress"),
    LocationData("Adequate Milker",             BASE_ID + 1176, "Fortress"),
    LocationData("Competent Milker",            BASE_ID + 1177, "Fortress"),
    LocationData("Skilled Milker",              BASE_ID + 1178, "Fortress"),
    LocationData("Proficient Milker",           BASE_ID + 1179, "Fortress"),
    LocationData("Talented Milker",             BASE_ID + 1180, "Fortress"),
    LocationData("Adept Milker",                BASE_ID + 1181, "Fortress"),
    LocationData("Expert Milker",               BASE_ID + 1182, "Fortress"),
    LocationData("Professional Milker",         BASE_ID + 1183, "Fortress"),
    LocationData("Accomplished Milker",         BASE_ID + 1184, "Fortress"),
    LocationData("Great Milker",                BASE_ID + 1185, "Fortress"),
    LocationData("Master Milker",               BASE_ID + 1186, "Fortress"),
    LocationData("High Master Milker",          BASE_ID + 1187, "Fortress"),
    LocationData("Grand Master Milker",         BASE_ID + 1188, "Fortress"),
    LocationData("Legendary Milker",            BASE_ID + 1189, "Fortress"),

    LocationData("Novice Cheese Maker",         BASE_ID + 1190, "Fortress"),
    LocationData("Adequate Cheese Maker",       BASE_ID + 1191, "Fortress"),
    LocationData("Competent Cheese Maker",      BASE_ID + 1192, "Fortress"),
    LocationData("Skilled Cheese Maker",        BASE_ID + 1193, "Fortress"),
    LocationData("Proficient Cheese Maker",     BASE_ID + 1194, "Fortress"),
    LocationData("Talented Cheese Maker",       BASE_ID + 1195, "Fortress"),
    LocationData("Adept Cheese Maker",          BASE_ID + 1196, "Fortress"),
    LocationData("Expert Cheese Maker",         BASE_ID + 1197, "Fortress"),
    LocationData("Professional Cheese Maker",   BASE_ID + 1198, "Fortress"),
    LocationData("Accomplished Cheese Maker",   BASE_ID + 1199, "Fortress"),
    LocationData("Great Cheese Maker",          BASE_ID + 1200, "Fortress"),
    LocationData("Master Cheese Maker",         BASE_ID + 1201, "Fortress"),
    LocationData("High Master Cheese Maker",    BASE_ID + 1202, "Fortress"),
    LocationData("Grand Master Cheese Maker",   BASE_ID + 1203, "Fortress"),
    LocationData("Legendary Cheese Maker",      BASE_ID + 1204, "Fortress"),

    LocationData("Novice Thresher",             BASE_ID + 1205, "Fortress"),
    LocationData("Adequate Thresher",           BASE_ID + 1206, "Fortress"),
    LocationData("Competent Thresher",          BASE_ID + 1207, "Fortress"),
    LocationData("Skilled Thresher",            BASE_ID + 1208, "Fortress"),
    LocationData("Proficient Thresher",         BASE_ID + 1209, "Fortress"),
    LocationData("Talented Thresher",           BASE_ID + 1210, "Fortress"),
    LocationData("Adept Thresher",              BASE_ID + 1211, "Fortress"),
    LocationData("Expert Thresher",             BASE_ID + 1212, "Fortress"),
    LocationData("Professional Thresher",       BASE_ID + 1213, "Fortress"),
    LocationData("Accomplished Thresher",       BASE_ID + 1214, "Fortress"),
    LocationData("Great Thresher",              BASE_ID + 1215, "Fortress"),
    LocationData("Master Thresher",             BASE_ID + 1216, "Fortress"),
    LocationData("High Master Thresher",        BASE_ID + 1217, "Fortress"),
    LocationData("Grand Master Thresher",       BASE_ID + 1218, "Fortress"),
    LocationData("Legendary Thresher",          BASE_ID + 1219, "Fortress"),

    LocationData("Novice Cook",                 BASE_ID + 1220, "Fortress"),
    LocationData("Adequate Cook",               BASE_ID + 1221, "Fortress"),
    LocationData("Competent Cook",              BASE_ID + 1222, "Fortress"),
    LocationData("Skilled Cook",                BASE_ID + 1223, "Fortress"),
    LocationData("Proficient Cook",             BASE_ID + 1224, "Fortress"),
    LocationData("Talented Cook",               BASE_ID + 1225, "Fortress"),
    LocationData("Adept Cook",                  BASE_ID + 1226, "Fortress"),
    LocationData("Expert Cook",                 BASE_ID + 1227, "Fortress"),
    LocationData("Professional Cook",           BASE_ID + 1228, "Fortress"),
    LocationData("Accomplished Cook",           BASE_ID + 1229, "Fortress"),
    LocationData("Great Cook",                  BASE_ID + 1230, "Fortress"),
    LocationData("Master Cook",                 BASE_ID + 1231, "Fortress"),
    LocationData("High Master Cook",            BASE_ID + 1232, "Fortress"),
    LocationData("Grand Master Cook",           BASE_ID + 1233, "Fortress"),
    LocationData("Legendary Cook",              BASE_ID + 1234, "Fortress"),

    LocationData("Novice Bone Carver",          BASE_ID + 1235, "Fortress"),
    LocationData("Adequate Bone Carver",        BASE_ID + 1236, "Fortress"),
    LocationData("Competent Bone Carver",       BASE_ID + 1237, "Fortress"),
    LocationData("Skilled Bone Carver",         BASE_ID + 1238, "Fortress"),
    LocationData("Proficient Bone Carver",      BASE_ID + 1239, "Fortress"),
    LocationData("Talented Bone Carver",        BASE_ID + 1240, "Fortress"),
    LocationData("Adept Bone Carver",           BASE_ID + 1241, "Fortress"),
    LocationData("Expert Bone Carver",          BASE_ID + 1242, "Fortress"),
    LocationData("Professional Bone Carver",    BASE_ID + 1243, "Fortress"),
    LocationData("Accomplished Bone Carver",    BASE_ID + 1244, "Fortress"),
    LocationData("Great Bone Carver",           BASE_ID + 1245, "Fortress"),
    LocationData("Master Bone Carver",          BASE_ID + 1246, "Fortress"),
    LocationData("High Master Bone Carver",     BASE_ID + 1247, "Fortress"),
    LocationData("Grand Master Bone Carver",    BASE_ID + 1248, "Fortress"),
    LocationData("Legendary Bone Carver",       BASE_ID + 1249, "Fortress"),

    LocationData("Novice Siege Operator",       BASE_ID + 1250, "Fortress"),
    LocationData("Adequate Siege Operator",     BASE_ID + 1251, "Fortress"),
    LocationData("Competent Siege Operator",    BASE_ID + 1252, "Fortress"),
    LocationData("Skilled Siege Operator",      BASE_ID + 1253, "Fortress"),
    LocationData("Proficient Siege Operator",   BASE_ID + 1254, "Fortress"),
    LocationData("Talented Siege Operator",     BASE_ID + 1255, "Fortress"),
    LocationData("Adept Siege Operator",        BASE_ID + 1256, "Fortress"),
    LocationData("Expert Siege Operator",       BASE_ID + 1257, "Fortress"),
    LocationData("Professional Siege Operator", BASE_ID + 1258, "Fortress"),
    LocationData("Accomplished Siege Operator", BASE_ID + 1259, "Fortress"),
    LocationData("Great Siege Operator",        BASE_ID + 1260, "Fortress"),
    LocationData("Master Siege Operator",       BASE_ID + 1261, "Fortress"),
    LocationData("High Master Siege Operator",  BASE_ID + 1262, "Fortress"),
    LocationData("Grand Master Siege Operator", BASE_ID + 1263, "Fortress"),
    LocationData("Legendary Siege Operator",    BASE_ID + 1264, "Fortress"),

    LocationData("Novice Mechanic",             BASE_ID + 1265, "Fortress"),
    LocationData("Adequate Mechanic",           BASE_ID + 1266, "Fortress"),
    LocationData("Competent Mechanic",          BASE_ID + 1267, "Fortress"),
    LocationData("Skilled Mechanic",            BASE_ID + 1268, "Fortress"),
    LocationData("Proficient Mechanic",         BASE_ID + 1269, "Fortress"),
    LocationData("Talented Mechanic",           BASE_ID + 1270, "Fortress"),
    LocationData("Adept Mechanic",              BASE_ID + 1271, "Fortress"),
    LocationData("Expert Mechanic",             BASE_ID + 1272, "Fortress"),
    LocationData("Professional Mechanic",       BASE_ID + 1273, "Fortress"),
    LocationData("Accomplished Mechanic",       BASE_ID + 1274, "Fortress"),
    LocationData("Great Mechanic",              BASE_ID + 1275, "Fortress"),
    LocationData("Master Mechanic",             BASE_ID + 1276, "Fortress"),
    LocationData("High Master Mechanic",        BASE_ID + 1277, "Fortress"),
    LocationData("Grand Master Mechanic",       BASE_ID + 1278, "Fortress"),
    LocationData("Legendary Mechanic",          BASE_ID + 1279, "Fortress"),

    LocationData("Novice Diagnostician",        BASE_ID + 1280, "Fortress"),
    LocationData("Adequate Diagnostician",      BASE_ID + 1281, "Fortress"),
    LocationData("Competent Diagnostician",     BASE_ID + 1282, "Fortress"),
    LocationData("Skilled Diagnostician",       BASE_ID + 1283, "Fortress"),
    LocationData("Proficient Diagnostician",    BASE_ID + 1284, "Fortress"),
    LocationData("Talented Diagnostician",      BASE_ID + 1285, "Fortress"),
    LocationData("Adept Diagnostician",         BASE_ID + 1286, "Fortress"),
    LocationData("Expert Diagnostician",        BASE_ID + 1287, "Fortress"),
    LocationData("Professional Diagnostician",  BASE_ID + 1288, "Fortress"),
    LocationData("Accomplished Diagnostician",  BASE_ID + 1289, "Fortress"),
    LocationData("Great Diagnostician",         BASE_ID + 1290, "Fortress"),
    LocationData("Master Diagnostician",        BASE_ID + 1291, "Fortress"),
    LocationData("High Master Diagnostician",   BASE_ID + 1292, "Fortress"),
    LocationData("Grand Master Diagnostician",  BASE_ID + 1293, "Fortress"),
    LocationData("Legendary Diagnostician",     BASE_ID + 1294, "Fortress"),

    LocationData("Novice Bone Doctor",          BASE_ID + 1295, "Fortress"),
    LocationData("Adequate Bone Doctor",        BASE_ID + 1296, "Fortress"),
    LocationData("Competent Bone Doctor",       BASE_ID + 1297, "Fortress"),
    LocationData("Skilled Bone Doctor",         BASE_ID + 1298, "Fortress"),
    LocationData("Proficient Bone Doctor",      BASE_ID + 1299, "Fortress"),
    LocationData("Talented Bone Doctor",        BASE_ID + 1300, "Fortress"),
    LocationData("Adept Bone Doctor",           BASE_ID + 1301, "Fortress"),
    LocationData("Expert Bone Doctor",          BASE_ID + 1302, "Fortress"),
    LocationData("Professional Bone Doctor",    BASE_ID + 1303, "Fortress"),
    LocationData("Accomplished Bone Doctor",    BASE_ID + 1304, "Fortress"),
    LocationData("Great Bone Doctor",           BASE_ID + 1305, "Fortress"),
    LocationData("Master Bone Doctor",          BASE_ID + 1306, "Fortress"),
    LocationData("High Master Bone Doctor",     BASE_ID + 1307, "Fortress"),
    LocationData("Grand Master Bone Doctor",    BASE_ID + 1308, "Fortress"),
    LocationData("Legendary Bone Doctor",       BASE_ID + 1309, "Fortress"),

    LocationData("Novice Wound Dresser",        BASE_ID + 1310, "Fortress"),
    LocationData("Adequate Wound Dresser",      BASE_ID + 1311, "Fortress"),
    LocationData("Competent Wound Dresser",     BASE_ID + 1312, "Fortress"),
    LocationData("Skilled Wound Dresser",       BASE_ID + 1313, "Fortress"),
    LocationData("Proficient Wound Dresser",    BASE_ID + 1314, "Fortress"),
    LocationData("Talented Wound Dresser",      BASE_ID + 1315, "Fortress"),
    LocationData("Adept Wound Dresser",         BASE_ID + 1316, "Fortress"),
    LocationData("Expert Wound Dresser",        BASE_ID + 1317, "Fortress"),
    LocationData("Professional Wound Dresser",  BASE_ID + 1318, "Fortress"),
    LocationData("Accomplished Wound Dresser",  BASE_ID + 1319, "Fortress"),
    LocationData("Great Wound Dresser",         BASE_ID + 1320, "Fortress"),
    LocationData("Master Wound Dresser",        BASE_ID + 1321, "Fortress"),
    LocationData("High Master Wound Dresser",   BASE_ID + 1322, "Fortress"),
    LocationData("Grand Master Wound Dresser",  BASE_ID + 1323, "Fortress"),
    LocationData("Legendary Wound Dresser",     BASE_ID + 1324, "Fortress"),

    LocationData("Novice Surgeon",              BASE_ID + 1325, "Fortress"),
    LocationData("Adequate Surgeon",            BASE_ID + 1326, "Fortress"),
    LocationData("Competent Surgeon",           BASE_ID + 1327, "Fortress"),
    LocationData("Skilled Surgeon",             BASE_ID + 1328, "Fortress"),
    LocationData("Proficient Surgeon",          BASE_ID + 1329, "Fortress"),
    LocationData("Talented Surgeon",            BASE_ID + 1330, "Fortress"),
    LocationData("Adept Surgeon",               BASE_ID + 1331, "Fortress"),
    LocationData("Expert Surgeon",              BASE_ID + 1332, "Fortress"),
    LocationData("Professional Surgeon",        BASE_ID + 1333, "Fortress"),
    LocationData("Accomplished Surgeon",        BASE_ID + 1334, "Fortress"),
    LocationData("Great Surgeon",               BASE_ID + 1335, "Fortress"),
    LocationData("Master Surgeon",              BASE_ID + 1336, "Fortress"),
    LocationData("High Master Surgeon",         BASE_ID + 1337, "Fortress"),
    LocationData("Grand Master Surgeon",        BASE_ID + 1338, "Fortress"),
    LocationData("Legendary Surgeon",           BASE_ID + 1339, "Fortress"),

    LocationData("Novice Suturer",              BASE_ID + 1340, "Fortress"),
    LocationData("Adequate Suturer",            BASE_ID + 1341, "Fortress"),
    LocationData("Competent Suturer",           BASE_ID + 1342, "Fortress"),
    LocationData("Skilled Suturer",             BASE_ID + 1343, "Fortress"),
    LocationData("Proficient Suturer",          BASE_ID + 1344, "Fortress"),
    LocationData("Talented Suturer",            BASE_ID + 1345, "Fortress"),
    LocationData("Adept Suturer",               BASE_ID + 1346, "Fortress"),
    LocationData("Expert Suturer",              BASE_ID + 1347, "Fortress"),
    LocationData("Professional Suturer",        BASE_ID + 1348, "Fortress"),
    LocationData("Accomplished Suturer",        BASE_ID + 1349, "Fortress"),
    LocationData("Great Suturer",               BASE_ID + 1350, "Fortress"),
    LocationData("Master Suturer",              BASE_ID + 1351, "Fortress"),
    LocationData("High Master Suturer",         BASE_ID + 1352, "Fortress"),
    LocationData("Grand Master Suturer",        BASE_ID + 1353, "Fortress"),
    LocationData("Legendary Suturer",           BASE_ID + 1354, "Fortress"),

    LocationData("Novice Wood Burner",          BASE_ID + 1355, "Fortress"),
    LocationData("Adequate Wood Burner",        BASE_ID + 1356, "Fortress"),
    LocationData("Competent Wood Burner",       BASE_ID + 1357, "Fortress"),
    LocationData("Skilled Wood Burner",         BASE_ID + 1358, "Fortress"),
    LocationData("Proficient Wood Burner",      BASE_ID + 1359, "Fortress"),
    LocationData("Talented Wood Burner",        BASE_ID + 1360, "Fortress"),
    LocationData("Adept Wood Burner",           BASE_ID + 1361, "Fortress"),
    LocationData("Expert Wood Burner",          BASE_ID + 1362, "Fortress"),
    LocationData("Professional Wood Burner",    BASE_ID + 1363, "Fortress"),
    LocationData("Accomplished Wood Burner",    BASE_ID + 1364, "Fortress"),
    LocationData("Great Wood Burner",           BASE_ID + 1365, "Fortress"),
    LocationData("Master Wood Burner",          BASE_ID + 1366, "Fortress"),
    LocationData("High Master Wood Burner",     BASE_ID + 1367, "Fortress"),
    LocationData("Grand Master Wood Burner",    BASE_ID + 1368, "Fortress"),
    LocationData("Legendary Wood Burner",       BASE_ID + 1369, "Fortress"),

    LocationData("Novice Lye Maker",            BASE_ID + 1370, "Fortress"),
    LocationData("Adequate Lye Maker",          BASE_ID + 1371, "Fortress"),
    LocationData("Competent Lye Maker",         BASE_ID + 1372, "Fortress"),
    LocationData("Skilled Lye Maker",           BASE_ID + 1373, "Fortress"),
    LocationData("Proficient Lye Maker",        BASE_ID + 1374, "Fortress"),
    LocationData("Talented Lye Maker",          BASE_ID + 1375, "Fortress"),
    LocationData("Adept Lye Maker",             BASE_ID + 1376, "Fortress"),
    LocationData("Expert Lye Maker",            BASE_ID + 1377, "Fortress"),
    LocationData("Professional Lye Maker",      BASE_ID + 1378, "Fortress"),
    LocationData("Accomplished Lye Maker",      BASE_ID + 1379, "Fortress"),
    LocationData("Great Lye Maker",             BASE_ID + 1380, "Fortress"),
    LocationData("Master Lye Maker",            BASE_ID + 1381, "Fortress"),
    LocationData("High Master Lye Maker",       BASE_ID + 1382, "Fortress"),
    LocationData("Grand Master Lye Maker",      BASE_ID + 1383, "Fortress"),
    LocationData("Legendary Lye Maker",         BASE_ID + 1384, "Fortress"),

    LocationData("Novice Potash Maker",         BASE_ID + 1385, "Fortress"),
    LocationData("Adequate Potash Maker",       BASE_ID + 1386, "Fortress"),
    LocationData("Competent Potash Maker",      BASE_ID + 1387, "Fortress"),
    LocationData("Skilled Potash Maker",        BASE_ID + 1388, "Fortress"),
    LocationData("Proficient Potash Maker",     BASE_ID + 1389, "Fortress"),
    LocationData("Talented Potash Maker",       BASE_ID + 1390, "Fortress"),
    LocationData("Adept Potash Maker",          BASE_ID + 1391, "Fortress"),
    LocationData("Expert Potash Maker",         BASE_ID + 1392, "Fortress"),
    LocationData("Professional Potash Maker",   BASE_ID + 1393, "Fortress"),
    LocationData("Accomplished Potash Maker",   BASE_ID + 1394, "Fortress"),
    LocationData("Great Potash Maker",          BASE_ID + 1395, "Fortress"),
    LocationData("Master Potash Maker",         BASE_ID + 1396, "Fortress"),
    LocationData("High Master Potash Maker",    BASE_ID + 1397, "Fortress"),
    LocationData("Grand Master Potash Maker",   BASE_ID + 1398, "Fortress"),
    LocationData("Legendary Potash Maker",      BASE_ID + 1399, "Fortress"),

    LocationData("Novice Dyer",                 BASE_ID + 1400, "Fortress"),
    LocationData("Adequate Dyer",               BASE_ID + 1401, "Fortress"),
    LocationData("Competent Dyer",              BASE_ID + 1402, "Fortress"),
    LocationData("Skilled Dyer",                BASE_ID + 1403, "Fortress"),
    LocationData("Proficient Dyer",             BASE_ID + 1404, "Fortress"),
    LocationData("Talented Dyer",               BASE_ID + 1405, "Fortress"),
    LocationData("Adept Dyer",                  BASE_ID + 1406, "Fortress"),
    LocationData("Expert Dyer",                 BASE_ID + 1407, "Fortress"),
    LocationData("Professional Dyer",           BASE_ID + 1408, "Fortress"),
    LocationData("Accomplished Dyer",           BASE_ID + 1409, "Fortress"),
    LocationData("Great Dyer",                  BASE_ID + 1410, "Fortress"),
    LocationData("Master Dyer",                 BASE_ID + 1411, "Fortress"),
    LocationData("High Master Dyer",            BASE_ID + 1412, "Fortress"),
    LocationData("Grand Master Dyer",           BASE_ID + 1413, "Fortress"),
    LocationData("Legendary Dyer",              BASE_ID + 1414, "Fortress"),

    LocationData("Novice Pump Operator",        BASE_ID + 1415, "Fortress"),
    LocationData("Adequate Pump Operator",      BASE_ID + 1416, "Fortress"),
    LocationData("Competent Pump Operator",     BASE_ID + 1417, "Fortress"),
    LocationData("Skilled Pump Operator",       BASE_ID + 1418, "Fortress"),
    LocationData("Proficient Pump Operator",    BASE_ID + 1419, "Fortress"),
    LocationData("Talented Pump Operator",      BASE_ID + 1420, "Fortress"),
    LocationData("Adept Pump Operator",         BASE_ID + 1421, "Fortress"),
    LocationData("Expert Pump Operator",        BASE_ID + 1422, "Fortress"),
    LocationData("Professional Pump Operator",  BASE_ID + 1423, "Fortress"),
    LocationData("Accomplished Pump Operator",  BASE_ID + 1424, "Fortress"),
    LocationData("Great Pump Operator",         BASE_ID + 1425, "Fortress"),
    LocationData("Master Pump Operator",        BASE_ID + 1426, "Fortress"),
    LocationData("High Master Pump Operator",   BASE_ID + 1427, "Fortress"),
    LocationData("Grand Master Pump Operator",  BASE_ID + 1428, "Fortress"),
    LocationData("Legendary Pump Operator",     BASE_ID + 1429, "Fortress"),

    LocationData("Novice Shearer",              BASE_ID + 1430, "Fortress"),
    LocationData("Adequate Shearer",            BASE_ID + 1431, "Fortress"),
    LocationData("Competent Shearer",           BASE_ID + 1432, "Fortress"),
    LocationData("Skilled Shearer",             BASE_ID + 1433, "Fortress"),
    LocationData("Proficient Shearer",          BASE_ID + 1434, "Fortress"),
    LocationData("Talented Shearer",            BASE_ID + 1435, "Fortress"),
    LocationData("Adept Shearer",               BASE_ID + 1436, "Fortress"),
    LocationData("Expert Shearer",              BASE_ID + 1437, "Fortress"),
    LocationData("Professional Shearer",        BASE_ID + 1438, "Fortress"),
    LocationData("Accomplished Shearer",        BASE_ID + 1439, "Fortress"),
    LocationData("Great Shearer",               BASE_ID + 1440, "Fortress"),
    LocationData("Master Shearer",              BASE_ID + 1441, "Fortress"),
    LocationData("High Master Shearer",         BASE_ID + 1442, "Fortress"),
    LocationData("Grand Master Shearer",        BASE_ID + 1443, "Fortress"),
    LocationData("Legendary Shearer",           BASE_ID + 1444, "Fortress"),

    LocationData("Novice Gelder",               BASE_ID + 1445, "Fortress"),
    LocationData("Adequate Gelder",             BASE_ID + 1446, "Fortress"),
    LocationData("Competent Gelder",            BASE_ID + 1447, "Fortress"),
    LocationData("Skilled Gelder",              BASE_ID + 1448, "Fortress"),
    LocationData("Proficient Gelder",           BASE_ID + 1449, "Fortress"),
    LocationData("Talented Gelder",             BASE_ID + 1450, "Fortress"),
    LocationData("Adept Gelder",                BASE_ID + 1451, "Fortress"),
    LocationData("Expert Gelder",               BASE_ID + 1452, "Fortress"),
    LocationData("Professional Gelder",         BASE_ID + 1453, "Fortress"),
    LocationData("Accomplished Gelder",         BASE_ID + 1454, "Fortress"),
    LocationData("Great Gelder",                BASE_ID + 1455, "Fortress"),
    LocationData("Master Gelder",               BASE_ID + 1456, "Fortress"),
    LocationData("High Master Gelder",          BASE_ID + 1457, "Fortress"),
    LocationData("Grand Master Gelder",         BASE_ID + 1458, "Fortress"),
    LocationData("Legendary Gelder",            BASE_ID + 1459, "Fortress"),

    LocationData("Novice Carpenter",            BASE_ID + 1460, "Fortress"),
    LocationData("Adequate Carpenter",          BASE_ID + 1461, "Fortress"),
    LocationData("Competent Carpenter",         BASE_ID + 1462, "Fortress"),
    LocationData("Skilled Carpenter",           BASE_ID + 1463, "Fortress"),
    LocationData("Proficient Carpenter",        BASE_ID + 1464, "Fortress"),
    LocationData("Talented Carpenter",          BASE_ID + 1465, "Fortress"),
    LocationData("Adept Carpenter",             BASE_ID + 1466, "Fortress"),
    LocationData("Expert Carpenter",            BASE_ID + 1467, "Fortress"),
    LocationData("Professional Carpenter",      BASE_ID + 1468, "Fortress"),
    LocationData("Accomplished Carpenter",      BASE_ID + 1469, "Fortress"),
    LocationData("Great Carpenter",             BASE_ID + 1470, "Fortress"),
    LocationData("Master Carpenter",            BASE_ID + 1471, "Fortress"),
    LocationData("High Master Carpenter",       BASE_ID + 1472, "Fortress"),
    LocationData("Grand Master Carpenter",      BASE_ID + 1473, "Fortress"),
    LocationData("Legendary Carpenter",         BASE_ID + 1474, "Fortress"),

    LocationData("Novice Mason",                BASE_ID + 1475, "Fortress"),
    LocationData("Adequate Mason",              BASE_ID + 1476, "Fortress"),
    LocationData("Competent Mason",             BASE_ID + 1477, "Fortress"),
    LocationData("Skilled Mason",               BASE_ID + 1478, "Fortress"),
    LocationData("Proficient Mason",            BASE_ID + 1479, "Fortress"),
    LocationData("Talented Mason",              BASE_ID + 1480, "Fortress"),
    LocationData("Adept Mason",                 BASE_ID + 1481, "Fortress"),
    LocationData("Expert Mason",                BASE_ID + 1482, "Fortress"),
    LocationData("Professional Mason",          BASE_ID + 1483, "Fortress"),
    LocationData("Accomplished Mason",          BASE_ID + 1484, "Fortress"),
    LocationData("Great Mason",                 BASE_ID + 1485, "Fortress"),
    LocationData("Master Mason",                BASE_ID + 1486, "Fortress"),
    LocationData("High Master Mason",           BASE_ID + 1487, "Fortress"),
    LocationData("Grand Master Mason",          BASE_ID + 1488, "Fortress"),
    LocationData("Legendary Mason",             BASE_ID + 1489, "Fortress"),

    LocationData("Novice Fish Dissector",       BASE_ID + 1490, "Fortress"),
    LocationData("Adequate Fish Dissector",     BASE_ID + 1491, "Fortress"),
    LocationData("Competent Fish Dissector",    BASE_ID + 1492, "Fortress"),
    LocationData("Skilled Fish Dissector",      BASE_ID + 1493, "Fortress"),
    LocationData("Proficient Fish Dissector",   BASE_ID + 1494, "Fortress"),
    LocationData("Talented Fish Dissector",     BASE_ID + 1495, "Fortress"),
    LocationData("Adept Fish Dissector",        BASE_ID + 1496, "Fortress"),
    LocationData("Expert Fish Dissector",       BASE_ID + 1497, "Fortress"),
    LocationData("Professional Fish Dissector", BASE_ID + 1498, "Fortress"),
    LocationData("Accomplished Fish Dissector", BASE_ID + 1499, "Fortress"),
    LocationData("Great Fish Dissector",        BASE_ID + 1500, "Fortress"),
    LocationData("Master Fish Dissector",       BASE_ID + 1501, "Fortress"),
    LocationData("High Master Fish Dissector",  BASE_ID + 1502, "Fortress"),
    LocationData("Grand Master Fish Dissector", BASE_ID + 1503, "Fortress"),
    LocationData("Legendary Fish Dissector",    BASE_ID + 1504, "Fortress"),

    LocationData("Novice Leatherworker",        BASE_ID + 1505, "Fortress"),
    LocationData("Adequate Leatherworker",      BASE_ID + 1506, "Fortress"),
    LocationData("Competent Leatherworker",     BASE_ID + 1507, "Fortress"),
    LocationData("Skilled Leatherworker",       BASE_ID + 1508, "Fortress"),
    LocationData("Proficient Leatherworker",    BASE_ID + 1509, "Fortress"),
    LocationData("Talented Leatherworker",      BASE_ID + 1510, "Fortress"),
    LocationData("Adept Leatherworker",         BASE_ID + 1511, "Fortress"),
    LocationData("Expert Leatherworker",        BASE_ID + 1512, "Fortress"),
    LocationData("Professional Leatherworker",  BASE_ID + 1513, "Fortress"),
    LocationData("Accomplished Leatherworker",  BASE_ID + 1514, "Fortress"),
    LocationData("Great Leatherworker",         BASE_ID + 1515, "Fortress"),
    LocationData("Master Leatherworker",        BASE_ID + 1516, "Fortress"),
    LocationData("High Master Leatherworker",   BASE_ID + 1517, "Fortress"),
    LocationData("Grand Master Leatherworker",  BASE_ID + 1518, "Fortress"),
    LocationData("Legendary Leatherworker",     BASE_ID + 1519, "Fortress"),

    LocationData("Novice Clothier",             BASE_ID + 1520, "Fortress"),
    LocationData("Adequate Clothier",           BASE_ID + 1521, "Fortress"),
    LocationData("Competent Clothier",          BASE_ID + 1522, "Fortress"),
    LocationData("Skilled Clothier",            BASE_ID + 1523, "Fortress"),
    LocationData("Proficient Clothier",         BASE_ID + 1524, "Fortress"),
    LocationData("Talented Clothier",           BASE_ID + 1525, "Fortress"),
    LocationData("Adept Clothier",              BASE_ID + 1526, "Fortress"),
    LocationData("Expert Clothier",             BASE_ID + 1527, "Fortress"),
    LocationData("Professional Clothier",       BASE_ID + 1528, "Fortress"),
    LocationData("Accomplished Clothier",       BASE_ID + 1529, "Fortress"),
    LocationData("Great Clothier",              BASE_ID + 1530, "Fortress"),
    LocationData("Master Clothier",             BASE_ID + 1531, "Fortress"),
    LocationData("High Master Clothier",        BASE_ID + 1532, "Fortress"),
    LocationData("Grand Master Clothier",       BASE_ID + 1533, "Fortress"),
    LocationData("Legendary Clothier",          BASE_ID + 1534, "Fortress"),

    LocationData("Novice Blacksmith",           BASE_ID + 1535, "Fortress"),
    LocationData("Adequate Blacksmith",         BASE_ID + 1536, "Fortress"),
    LocationData("Competent Blacksmith",        BASE_ID + 1537, "Fortress"),
    LocationData("Skilled Blacksmith",          BASE_ID + 1538, "Fortress"),
    LocationData("Proficient Blacksmith",       BASE_ID + 1539, "Fortress"),
    LocationData("Talented Blacksmith",         BASE_ID + 1540, "Fortress"),
    LocationData("Adept Blacksmith",            BASE_ID + 1541, "Fortress"),
    LocationData("Expert Blacksmith",           BASE_ID + 1542, "Fortress"),
    LocationData("Professional Blacksmith",     BASE_ID + 1543, "Fortress"),
    LocationData("Accomplished Blacksmith",     BASE_ID + 1544, "Fortress"),
    LocationData("Great Blacksmith",            BASE_ID + 1545, "Fortress"),
    LocationData("Master Blacksmith",           BASE_ID + 1546, "Fortress"),
    LocationData("High Master Blacksmith",      BASE_ID + 1547, "Fortress"),
    LocationData("Grand Master Blacksmith",     BASE_ID + 1548, "Fortress"),
    LocationData("Legendary Blacksmith",        BASE_ID + 1549, "Fortress"),

    LocationData("Novice Bowyer",               BASE_ID + 1550, "Fortress"),
    LocationData("Adequate Bowyer",             BASE_ID + 1551, "Fortress"),
    LocationData("Competent Bowyer",            BASE_ID + 1552, "Fortress"),
    LocationData("Skilled Bowyer",              BASE_ID + 1553, "Fortress"),
    LocationData("Proficient Bowyer",           BASE_ID + 1554, "Fortress"),
    LocationData("Talented Bowyer",             BASE_ID + 1555, "Fortress"),
    LocationData("Adept Bowyer",                BASE_ID + 1556, "Fortress"),
    LocationData("Expert Bowyer",               BASE_ID + 1557, "Fortress"),
    LocationData("Professional Bowyer",         BASE_ID + 1558, "Fortress"),
    LocationData("Accomplished Bowyer",         BASE_ID + 1559, "Fortress"),
    LocationData("Great Bowyer",                BASE_ID + 1560, "Fortress"),
    LocationData("Master Bowyer",               BASE_ID + 1561, "Fortress"),
    LocationData("High Master Bowyer",          BASE_ID + 1562, "Fortress"),
    LocationData("Grand Master Bowyer",         BASE_ID + 1563, "Fortress"),
    LocationData("Legendary Bowyer",            BASE_ID + 1564, "Fortress"),

    LocationData("Novice Soaper",               BASE_ID + 1565, "Fortress"),
    LocationData("Adequate Soaper",             BASE_ID + 1566, "Fortress"),
    LocationData("Competent Soaper",            BASE_ID + 1567, "Fortress"),
    LocationData("Skilled Soaper",              BASE_ID + 1568, "Fortress"),
    LocationData("Proficient Soaper",           BASE_ID + 1569, "Fortress"),
    LocationData("Talented Soaper",             BASE_ID + 1570, "Fortress"),
    LocationData("Adept Soaper",                BASE_ID + 1571, "Fortress"),
    LocationData("Expert Soaper",               BASE_ID + 1572, "Fortress"),
    LocationData("Professional Soaper",         BASE_ID + 1573, "Fortress"),
    LocationData("Accomplished Soaper",         BASE_ID + 1574, "Fortress"),
    LocationData("Great Soaper",                BASE_ID + 1575, "Fortress"),
    LocationData("Master Soaper",               BASE_ID + 1576, "Fortress"),
    LocationData("High Master Soaper",          BASE_ID + 1577, "Fortress"),
    LocationData("Grand Master Soaper",         BASE_ID + 1578, "Fortress"),
    LocationData("Legendary Soaper",            BASE_ID + 1579, "Fortress"),

    LocationData("Novice Potter",               BASE_ID + 1580, "Fortress"),
    LocationData("Adequate Potter",             BASE_ID + 1581, "Fortress"),
    LocationData("Competent Potter",            BASE_ID + 1582, "Fortress"),
    LocationData("Skilled Potter",              BASE_ID + 1583, "Fortress"),
    LocationData("Proficient Potter",           BASE_ID + 1584, "Fortress"),
    LocationData("Talented Potter",             BASE_ID + 1585, "Fortress"),
    LocationData("Adept Potter",                BASE_ID + 1586, "Fortress"),
    LocationData("Expert Potter",               BASE_ID + 1587, "Fortress"),
    LocationData("Professional Potter",         BASE_ID + 1588, "Fortress"),
    LocationData("Accomplished Potter",         BASE_ID + 1589, "Fortress"),
    LocationData("Great Potter",                BASE_ID + 1590, "Fortress"),
    LocationData("Master Potter",               BASE_ID + 1591, "Fortress"),
    LocationData("High Master Potter",          BASE_ID + 1592, "Fortress"),
    LocationData("Grand Master Potter",         BASE_ID + 1593, "Fortress"),
    LocationData("Legendary Potter",            BASE_ID + 1594, "Fortress"),

    LocationData("Novice Glazer",               BASE_ID + 1595, "Fortress"),
    LocationData("Adequate Glazer",             BASE_ID + 1596, "Fortress"),
    LocationData("Competent Glazer",            BASE_ID + 1597, "Fortress"),
    LocationData("Skilled Glazer",              BASE_ID + 1598, "Fortress"),
    LocationData("Proficient Glazer",           BASE_ID + 1599, "Fortress"),
    LocationData("Talented Glazer",             BASE_ID + 1600, "Fortress"),
    LocationData("Adept Glazer",                BASE_ID + 1601, "Fortress"),
    LocationData("Expert Glazer",               BASE_ID + 1602, "Fortress"),
    LocationData("Professional Glazer",         BASE_ID + 1603, "Fortress"),
    LocationData("Accomplished Glazer",         BASE_ID + 1604, "Fortress"),
    LocationData("Great Glazer",                BASE_ID + 1605, "Fortress"),
    LocationData("Master Glazer",               BASE_ID + 1606, "Fortress"),
    LocationData("High Master Glazer",          BASE_ID + 1607, "Fortress"),
    LocationData("Grand Master Glazer",         BASE_ID + 1608, "Fortress"),
    LocationData("Legendary Glazer",            BASE_ID + 1609, "Fortress"),

    LocationData("Novice Presser",              BASE_ID + 1610, "Fortress"),
    LocationData("Adequate Presser",            BASE_ID + 1611, "Fortress"),
    LocationData("Competent Presser",           BASE_ID + 1612, "Fortress"),
    LocationData("Skilled Presser",             BASE_ID + 1613, "Fortress"),
    LocationData("Proficient Presser",          BASE_ID + 1614, "Fortress"),
    LocationData("Talented Presser",            BASE_ID + 1615, "Fortress"),
    LocationData("Adept Presser",               BASE_ID + 1616, "Fortress"),
    LocationData("Expert Presser",              BASE_ID + 1617, "Fortress"),
    LocationData("Professional Presser",        BASE_ID + 1618, "Fortress"),
    LocationData("Accomplished Presser",        BASE_ID + 1619, "Fortress"),
    LocationData("Great Presser",               BASE_ID + 1620, "Fortress"),
    LocationData("Master Presser",              BASE_ID + 1621, "Fortress"),
    LocationData("High Master Presser",         BASE_ID + 1622, "Fortress"),
    LocationData("Grand Master Presser",        BASE_ID + 1623, "Fortress"),
    LocationData("Legendary Presser",           BASE_ID + 1624, "Fortress"),

    LocationData("Novice Beekeeper",            BASE_ID + 1625, "Fortress"),
    LocationData("Adequate Beekeeper",          BASE_ID + 1626, "Fortress"),
    LocationData("Competent Beekeeper",         BASE_ID + 1627, "Fortress"),
    LocationData("Skilled Beekeeper",           BASE_ID + 1628, "Fortress"),
    LocationData("Proficient Beekeeper",        BASE_ID + 1629, "Fortress"),
    LocationData("Talented Beekeeper",          BASE_ID + 1630, "Fortress"),
    LocationData("Adept Beekeeper",             BASE_ID + 1631, "Fortress"),
    LocationData("Expert Beekeeper",            BASE_ID + 1632, "Fortress"),
    LocationData("Professional Beekeeper",      BASE_ID + 1633, "Fortress"),
    LocationData("Accomplished Beekeeper",      BASE_ID + 1634, "Fortress"),
    LocationData("Great Beekeeper",             BASE_ID + 1635, "Fortress"),
    LocationData("Master Beekeeper",            BASE_ID + 1636, "Fortress"),
    LocationData("High Master Beekeeper",       BASE_ID + 1637, "Fortress"),
    LocationData("Grand Master Beekeeper",      BASE_ID + 1638, "Fortress"),
    LocationData("Legendary Beekeeper",         BASE_ID + 1639, "Fortress"),

    LocationData("Novice Wax Worker",           BASE_ID + 1640, "Fortress"),
    LocationData("Adequate Wax Worker",         BASE_ID + 1641, "Fortress"),
    LocationData("Competent Wax Worker",        BASE_ID + 1642, "Fortress"),
    LocationData("Skilled Wax Worker",          BASE_ID + 1643, "Fortress"),
    LocationData("Proficient Wax Worker",       BASE_ID + 1644, "Fortress"),
    LocationData("Talented Wax Worker",         BASE_ID + 1645, "Fortress"),
    LocationData("Adept Wax Worker",            BASE_ID + 1646, "Fortress"),
    LocationData("Expert Wax Worker",           BASE_ID + 1647, "Fortress"),
    LocationData("Professional Wax Worker",     BASE_ID + 1648, "Fortress"),
    LocationData("Accomplished Wax Worker",     BASE_ID + 1649, "Fortress"),
    LocationData("Great Wax Worker",            BASE_ID + 1650, "Fortress"),
    LocationData("Master Wax Worker",           BASE_ID + 1651, "Fortress"),
    LocationData("High Master Wax Worker",      BASE_ID + 1652, "Fortress"),
    LocationData("Grand Master Wax Worker",     BASE_ID + 1653, "Fortress"),
    LocationData("Legendary Wax Worker",        BASE_ID + 1654, "Fortress"),

    LocationData("Novice Papermaker",           BASE_ID + 1655, "Fortress"),
    LocationData("Adequate Papermaker",         BASE_ID + 1656, "Fortress"),
    LocationData("Competent Papermaker",        BASE_ID + 1657, "Fortress"),
    LocationData("Skilled Papermaker",          BASE_ID + 1658, "Fortress"),
    LocationData("Proficient Papermaker",       BASE_ID + 1659, "Fortress"),
    LocationData("Talented Papermaker",         BASE_ID + 1660, "Fortress"),
    LocationData("Adept Papermaker",            BASE_ID + 1661, "Fortress"),
    LocationData("Expert Papermaker",           BASE_ID + 1662, "Fortress"),
    LocationData("Professional Papermaker",     BASE_ID + 1663, "Fortress"),
    LocationData("Accomplished Papermaker",     BASE_ID + 1664, "Fortress"),
    LocationData("Great Papermaker",            BASE_ID + 1665, "Fortress"),
    LocationData("Master Papermaker",           BASE_ID + 1666, "Fortress"),
    LocationData("High Master Papermaker",      BASE_ID + 1667, "Fortress"),
    LocationData("Grand Master Papermaker",     BASE_ID + 1668, "Fortress"),
    LocationData("Legendary Papermaker",        BASE_ID + 1669, "Fortress"),

    LocationData("Novice Bookbinder",           BASE_ID + 1670, "Fortress"),
    LocationData("Adequate Bookbinder",         BASE_ID + 1671, "Fortress"),
    LocationData("Competent Bookbinder",        BASE_ID + 1672, "Fortress"),
    LocationData("Skilled Bookbinder",          BASE_ID + 1673, "Fortress"),
    LocationData("Proficient Bookbinder",       BASE_ID + 1674, "Fortress"),
    LocationData("Talented Bookbinder",         BASE_ID + 1675, "Fortress"),
    LocationData("Adept Bookbinder",            BASE_ID + 1676, "Fortress"),
    LocationData("Expert Bookbinder",           BASE_ID + 1677, "Fortress"),
    LocationData("Professional Bookbinder",     BASE_ID + 1678, "Fortress"),
    LocationData("Accomplished Bookbinder",     BASE_ID + 1679, "Fortress"),
    LocationData("Great Bookbinder",            BASE_ID + 1680, "Fortress"),
    LocationData("Master Bookbinder",           BASE_ID + 1681, "Fortress"),
    LocationData("High Master Bookbinder",      BASE_ID + 1682, "Fortress"),
    LocationData("Grand Master Bookbinder",     BASE_ID + 1683, "Fortress"),
    LocationData("Legendary Bookbinder",        BASE_ID + 1684, "Fortress"),

    LocationData("Novice Record Keeper",        BASE_ID + 1685, "Fortress"),
    LocationData("Adequate Record Keeper",      BASE_ID + 1686, "Fortress"),
    LocationData("Competent Record Keeper",     BASE_ID + 1687, "Fortress"),
    LocationData("Skilled Record Keeper",       BASE_ID + 1688, "Fortress"),
    LocationData("Proficient Record Keeper",    BASE_ID + 1689, "Fortress"),
    LocationData("Talented Record Keeper",      BASE_ID + 1690, "Fortress"),
    LocationData("Adept Record Keeper",         BASE_ID + 1691, "Fortress"),
    LocationData("Expert Record Keeper",        BASE_ID + 1692, "Fortress"),
    LocationData("Professional Record Keeper",  BASE_ID + 1693, "Fortress"),
    LocationData("Accomplished Record Keeper",  BASE_ID + 1694, "Fortress"),
    LocationData("Great Record Keeper",         BASE_ID + 1695, "Fortress"),
    LocationData("Master Record Keeper",        BASE_ID + 1696, "Fortress"),
    LocationData("High Master Record Keeper",   BASE_ID + 1697, "Fortress"),
    LocationData("Grand Master Record Keeper",  BASE_ID + 1698, "Fortress"),
    LocationData("Legendary Record Keeper",     BASE_ID + 1699, "Fortress"),

    LocationData("Novice Orginizer",            BASE_ID + 1700, "Fortress"),
    LocationData("Adequate Orginizer",          BASE_ID + 1701, "Fortress"),
    LocationData("Competent Orginizer",         BASE_ID + 1702, "Fortress"),
    LocationData("Skilled Orginizer",           BASE_ID + 1703, "Fortress"),
    LocationData("Proficient Orginizer",        BASE_ID + 1704, "Fortress"),
    LocationData("Talented Orginizer",          BASE_ID + 1705, "Fortress"),
    LocationData("Adept Orginizer",             BASE_ID + 1706, "Fortress"),
    LocationData("Expert Orginizer",            BASE_ID + 1707, "Fortress"),
    LocationData("Professional Orginizer",      BASE_ID + 1708, "Fortress"),
    LocationData("Accomplished Orginizer",      BASE_ID + 1709, "Fortress"),
    LocationData("Great Orginizer",             BASE_ID + 1710, "Fortress"),
    LocationData("Master Orginizer",            BASE_ID + 1711, "Fortress"),
    LocationData("High Master Orginizer",       BASE_ID + 1712, "Fortress"),
    LocationData("Grand Master Orginizer",      BASE_ID + 1713, "Fortress"),
    LocationData("Legendary Orginizer",         BASE_ID + 1714, "Fortress"),

    LocationData("Novice Appraiser",            BASE_ID + 1715, "Fortress"),
    LocationData("Adequate Appraiser",          BASE_ID + 1716, "Fortress"),
    LocationData("Competent Appraiser",         BASE_ID + 1717, "Fortress"),
    LocationData("Skilled Appraiser",           BASE_ID + 1718, "Fortress"),
    LocationData("Proficient Appraiser",        BASE_ID + 1719, "Fortress"),
    LocationData("Talented Appraiser",          BASE_ID + 1720, "Fortress"),
    LocationData("Adept Appraiser",             BASE_ID + 1721, "Fortress"),
    LocationData("Expert Appraiser",            BASE_ID + 1722, "Fortress"),
    LocationData("Professional Appraiser",      BASE_ID + 1723, "Fortress"),
    LocationData("Accomplished Appraiser",      BASE_ID + 1724, "Fortress"),
    LocationData("Great Appraiser",             BASE_ID + 1725, "Fortress"),
    LocationData("Master Appraiser",            BASE_ID + 1726, "Fortress"),
    LocationData("High Master Appraiser",       BASE_ID + 1727, "Fortress"),
    LocationData("Grand Master Appraiser",      BASE_ID + 1728, "Fortress"),
    LocationData("Legendary Appraiser",         BASE_ID + 1729, "Fortress"),
]


# Craft locations are NOT included here. They are computed deterministically by
# craftsanity.build_craft_location_table() and merged into the World's
# location_name_to_id in __init__.py (see _FULL_LOCATION_TABLE). Keeping them out
# of this module avoids a circular import (craftsanity imports from locations).
ALL_LOCATIONS: list[LocationData] = (
    WEALTH_LOCATIONS + PRODUCTION_LOCATIONS + TRADE_LOCATIONS
    + STATUS_LOCATIONS + TITLE_LOCATIONS + MINING_LOCATIONS
    + FARMING_LOCATIONS + INFRASTRUCTURE_LOCATIONS
    + BIOLOGY_LOCATIONS + ENDGAME_LOCATIONS + JOB_SKILLS
)
LOCATION_TABLE: dict[str, int] = {loc.name: loc.ap_id for loc in ALL_LOCATIONS}
